id: I4E914622
ocr_import_info:
  bdrc_scan_id: W1AC20
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:01:25.074816
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC20
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC20
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐབས་བཞི་པའི་སྡོམ་འགྲེལ་དང་ཤེས་ཁྱད་བྱེད་ངོའི་མཚན་ཉིད་བཞིའི་རྣམ་གཞག
  languages:
  - bo
  author: གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོ།
bases:
  I2PD18430:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18430
      total_pages: 358
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I2PD18430.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
